// 病理数据 mock - 基于真实病理数据

// 姓名脱敏处理函数
function desensitizeName(name: string): string {
  if (!name || name.length <= 1) return name;
  return `${name.charAt(0)}*`;
}

// 身份证号脱敏处理函数
function desensitizeIdCard(idCard: string): string {
  if (!idCard || idCard.length < 4) return idCard;
  return `****${idCard.substring(idCard.length - 4)}`;
}

function getPathologyData(page = 1, pageSize = 10) {
  const allData = [
    {
      reportTime: '2019/4/17 11:18',
      inspectionItem: '病理诊断',
      result: '腺癌，中-低分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('朱金兰'),
      idCard: desensitizeIdCard('532224195310100000'),
      hospitalNo: 'ZY240001272777',
      inspectionDate: '20190417',
      patientType: '住院',
      pathologyNo: '2019-03959',
      reportDoctor: '胡红艳',
      reviewDoctor: '胡红艳',
      diagnosis: '乙状结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤靶向治疗',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: '4b',
      nStage: '2',
      mStage: '1',
      occupation: '农民',
      bloodType: '未查',
      address: '云南省昆明市西山区福信路18号',
      phone: '13708499597',
      workUnit: '云南省昆明市西山区福信路18号',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"回盲部升结肠乙状结肠直肠及肿瘤"肠管切除标本两段，乙状结肠及直肠长25cm，一切缘周径4cm，另一切缘周径6cm，距一切缘8cm，另一切缘7cm处见一肿块，肿块大小7x5x4cm，肿块切面灰白灰黄实性质中，肿块侵犯浆膜层，并与第二段肠管回盲部粘连。升结肠及回盲部肠管长20cm，一切缘周径2cm，另一切缘周径4cm，距一切缘3cm，另一切缘15cm升结肠处见一溃疡区域，范围2x1.5cm；距一切缘8cm，另一切缘5cm回盲部与第一段肠管乙状结肠肠壁粘连，浆膜面受肿块侵犯；另触及阑尾一根，长3cm，直径0.5cm，肉眼见肿瘤侵犯。另触及肠系膜淋巴结数枚，另送"上切缘"带吻合器、"下切缘"、"肠系膜下动脉根部淋巴结"、"右输卵管表面结节"、"右侧圆韧带及卵巢肿瘤"灰褐组织一块，大小4x4x3cm，疑似卵巢大小2x1x1cm，疑似肿块大小3x2x1cm，切面灰白灰黄实性质中，疑似圆韧带大小4x2x1cm。',
      detailedPathologyDiagnosis:
        '<"回盲部升结肠乙状结肠直肠及肿瘤">两个肿块：腺癌，中-低分化，癌组织浸润肠壁全层达周围脂肪组织，局部累及神经，于镜下未见明确脉管内癌栓；标本两切缘及另送"上切缘、下切缘"于镜下未见癌组织；肠系膜淋巴结（0/13）于镜下未见癌转移，见肿瘤沉积结节两枚；"肠系膜下动脉根部淋巴结"（0/2）于镜下未见癌转移；另送"右输卵管表面结节"、"右侧圆韧带及卵巢肿瘤"慢性炎伴间质纤维化，未见癌组织，并见少许卵巢及输卵管组织。补充取材：阑尾：慢性炎，局部浆膜层见癌组织。  Vg：纤维组织阳性',
    },
    {
      reportTime: '2019/4/22 9:46',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('郭妃'),
      idCard: desensitizeIdCard('532325197002220000'),
      hospitalNo: 'ZY030001272623',
      inspectionDate: '20190422',
      patientType: '住院',
      pathologyNo: '2019-04227',
      reportDoctor: '张宗梅',
      reviewDoctor: '张宗梅',
      diagnosis: '肺占位性病变',
      hospitalDiagnosis: '肺部继发性恶性肿瘤',
      pathologyDiagnosis: '转移性腺癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: '1b',
      nStage: '0',
      mStage: '0',
      occupation: '其他',
      bloodType: 'B',
      address: '云南省楚雄彝族自治州姚安县',
      phone: '-',
      workUnit: '云南省楚雄彝族自治州姚安县',
      personalHistory:
        '生于原籍，久居云南省楚雄彝族自治州姚安县栋川镇郭家凹村委会郭三组73号，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有适龄婚育岁结婚，配偶身体情况：，育子女。',
      menstrualHistory: '"初潮岁，月经  量:，颜色:	月经情况:,孕胎产胎存胎"',
      fertilityHistory: '月经情况:",孕胎产胎存胎',
      grossAppearance:
        '"右半结肠及肿瘤"肠管切除标本一段，回肠长3cm，结肠长21cm，回肠切缘周径3cm，结肠切缘周径4cm，距回盲瓣13cm，结肠切缘5cm处见一溃疡型肿块，肿块大小3x2x1.5cm，肿块切面灰白实性质中，回盲部见阑尾一根，长6cm，直径0.5cm，附网膜组织一堆，总积6x5x4cm，未触及明显结节及淋巴结，肠系膜触及淋巴结数枚，另送袋装淋巴结一组。',
      detailedPathologyDiagnosis:
        '<"右半结肠及肿瘤">腺癌，中分化，癌组织浸润肠壁固有层肌全层达肠周脂肪组织；回肠切缘、结肠切缘、环周切缘、阑尾、网膜组织未见癌组织；肠系膜淋巴结（0/17)、"结肠中动脉根部淋巴结"（0/1）未见癌转移。  Vg：纤维组织阳性  Ag：银纤维阳性',
    },
    {
      reportTime: '2018/12/29 8:19',
      inspectionItem: '病理诊断',
      result: '腺癌，中-高分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('郭华'),
      idCard: desensitizeIdCard('532428194203161000'),
      hospitalNo: 'ZY030001263603',
      inspectionDate: '20181229',
      patientType: '住院',
      pathologyNo: '2018-16459',
      reportDoctor: '张宗梅',
      reviewDoctor: '张宗梅',
      diagnosis: '直肠恶性肿瘤',
      hospitalDiagnosis: '直肠恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IIA',
      clinicalStage: '',
      tStage: '3',
      nStage: '0',
      mStage: '0',
      occupation: '其他',
      bloodType: 'A',
      address: '戛洒镇戛洒中学2幢1单元201室',
      phone: '13888985063',
      workUnit: '无',
      personalHistory:
        '生于原籍，久居云南省玉溪市新平彝族傣族自治县桂山街道王家城，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有23岁结婚，配偶身体情况：已故，育3子0女。',
      menstrualHistory:
        '"初潮14岁，月经  量:中等，颜色:正常	月经情况:无血块、无痛经,孕3胎产3胎存3胎"',
      fertilityHistory: '月经情况:无血块、无痛经",孕3胎产3胎存3胎',
      grossAppearance:
        '"右半结肠及肿瘤"肠管切除标本一段，回肠长12cm，结肠长21cm，回肠切缘周径4cm，结肠切缘周径7cm，距结肠切缘10cm回盲瓣7cm处见一溃疡性肿块，大小5x4x2cm，切面灰白实性质中。于回盲瓣见阑尾一根，长约5.5cm，直径0.5cm。附网膜组织一堆，总积17x13x10cm，未触及明显结节及淋巴结。肠系膜触及淋巴结数枚。',
      detailedPathologyDiagnosis:
        '<"右半结肠及肿瘤">腺癌,中-高分化，癌组织浸润至肠壁全层；标本回肠切缘、结肠切缘、环周切缘、网膜组织未见癌组织；肠系膜动脉根部淋巴结(0/1)、回肠系膜淋巴结(0/9)、结肠系膜淋巴结(0/13)未见癌转移。  Vg:胶原纤维+。',
    },
    {
      reportTime: '2019/2/18 10:31',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('罗甫秦'),
      idCard: desensitizeIdCard('530112194310040000'),
      hospitalNo: 'ZY060001267185',
      inspectionDate: '20190218',
      patientType: '住院',
      pathologyNo: '2019-01335',
      reportDoctor: '郭姜艳',
      reviewDoctor: '郭姜艳',
      diagnosis: '降结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤中医治疗',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IIIC',
      clinicalStage: '',
      tStage: '4b',
      nStage: '1a',
      mStage: '0',
      occupation: '退(离)休人员',
      bloodType: '不详',
      address: '云南省昆明市西山区海口云南化学工业建设公司39幢3单元6号',
      phone: '13888566440',
      workUnit: '不详',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"左半结肠"肠管切除标本一段，长10cm，一切缘周径2cm，另一切缘周径3cm，距一切缘5cm，另一切缘1cm处见一溃疡隆起型肿块，肿块大小2x2x0.7cm，切面灰白灰红实性质中，肠系膜触及淋巴结数枚，另送"上切缘"带吻合器，"下切缘"。',
      detailedPathologyDiagnosis:
        '<"左半结肠">腺癌，中分化，癌组织浸润肠壁固有肌层全层达浆膜下脂肪组织。标本一切缘、另一切缘、环周切缘、"上切缘"、"下切缘"于镜下未见癌组织。肠系膜淋巴结（1/8）于镜下见癌转移。  VG:纤维组织阳性。',
    },
    {
      reportTime: '2019/4/26 10:40',
      inspectionItem: '病理诊断',
      result: '转移性腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('杜惠云'),
      idCard: desensitizeIdCard('530123197511042000'),
      hospitalNo: 'ZY040001428265',
      inspectionDate: '20190426',
      patientType: '住院',
      pathologyNo: '2019-04482',
      reportDoctor: '郭姜艳',
      reviewDoctor: '郭姜艳',
      diagnosis: '乙状结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤终末期化疗',
      pathologyDiagnosis: '转移性腺癌',
      tnmStage: 'IVB',
      clinicalStage: '',
      tStage: 'x',
      nStage: 'x',
      mStage: '1b',
      occupation: '专业技术人员',
      bloodType: 'AB',
      address: '云南省安宁市连然街道办事处一碗水村111号',
      phone: '13759585989',
      workUnit: '云南省安宁市人民医院',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"宫颈"带针头宫颈锥切标本一个，大小1.5x1.5x1cm，另送"颈管"灰褐组织一块，大小2x1.5x0.3cm，"颈管搔刮"灰褐胶冻样碎组织一堆，总积1x1x0.5cm。',
      detailedPathologyDiagnosis:
        '<"宫颈">宫颈各点呈慢性活动性炎改变，伴部分腺体鳞化，个别点灶区CINI。标本锥顶及锥底各切缘于镜下未见CIN病变。另送"颈管"慢性炎。"颈管搔刮物"镜下示黏液渗出物及破碎颈管腺体。  VG:纤维组织阳性',
    },
    {
      reportTime: '2019/6/17 9:59',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('施崇武'),
      idCard: desensitizeIdCard('530122195002130000'),
      hospitalNo: 'ZY170001276969',
      inspectionDate: '20190617',
      patientType: '住院',
      pathologyNo: '2019-06899',
      reportDoctor: '袁婧',
      reviewDoctor: '袁婧',
      diagnosis: '横结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤支持治疗',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'ⅢB',
      clinicalStage: '',
      tStage: '4a',
      nStage: '1b',
      mStage: '0',
      occupation: '其他',
      bloodType: '未查',
      address: '云南省昆明市晋宁县25幢3单元506号',
      phone: '13529099668',
      workUnit: '-',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"左半结肠及肿瘤"肠管切除标本一段，长25cm，一切缘周径6cm，，另一切缘周径5cm，距一切缘5cm，另一切缘8cm处见一肿块，大小3x2x1cm。肿块切面灰白，实性，质中，肠系膜触及淋巴结数枚，附网膜组织一堆，总积9x6x2cm，其间未触及明显结节。另送"肠系膜下血管"灰黄组织两块，总积2x2x0.6cm。',
      detailedPathologyDiagnosis:
        '<"左半结肠及肿瘤">腺癌，中分化，癌组织浸润肠壁全层达周围脂肪组织，可见脉管内癌栓；标本两切缘、环周切缘、网膜组织于镜下未见癌组织；肠系膜LN（2/12）见癌转移；肠系膜动脉根部淋LN（0/1）、"肠系膜下血管"（0/5）于镜下未见癌转移。  Vg：纤维组织阳性',
    },
    {
      reportTime: '2019/3/12 14:30',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('李树花'),
      idCard: desensitizeIdCard('53352219850828164X'),
      hospitalNo: 'ZY020001269664',
      inspectionDate: '20190312',
      patientType: '住院',
      pathologyNo: '2019-02261',
      reportDoctor: '吴琳',
      reviewDoctor: '吴琳',
      diagnosis: '乙状结肠恶性肿瘤',
      hospitalDiagnosis: '乙状结肠恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IIIC',
      clinicalStage: '',
      tStage: '3',
      nStage: '2b',
      mStage: '0',
      occupation: '其他',
      bloodType: '未查',
      address: '云南省临沧市凤庆县凤山镇落星村委会李家组30号附4号',
      phone: '-',
      workUnit: '云南省临沧市凤庆县凤山镇落星村委会李家组30号附4号',
      personalHistory:
        '生于原籍，久居云南省临沧市凤庆县凤山镇落星村委会李家组30号附4号，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有26岁结婚，配偶身体情况：健在，育0子1女。',
      menstrualHistory:
        '"初潮14岁，月经  量:中等，颜色:正常	月经情况:无血块、无痛经,孕1胎产1胎存1胎"',
      fertilityHistory: '月经情况:无血块、无痛经",孕1胎产1胎存1胎',
      grossAppearance: '"右乳肿块"灰白灰黄灰褐碎组织一堆，总积4x3x2cm。',
      detailedPathologyDiagnosis:
        '<"右乳肿块">肉芽肿性小叶性乳腺炎。  VG：胶原纤维阳性。',
    },
    {
      reportTime: '2019/6/19 9:58',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('和积华'),
      idCard: desensitizeIdCard('533221195512040000'),
      hospitalNo: 'ZY030001277749',
      inspectionDate: '20190619',
      patientType: '住院',
      pathologyNo: '2019-06999',
      reportDoctor: '袁婧',
      reviewDoctor: '袁婧',
      diagnosis: '肝部和肝内胆管继发性恶性肿瘤',
      hospitalDiagnosis: '肝部和肝内胆管继发性恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: 'X',
      nStage: 'X',
      mStage: '1',
      occupation: '退(离)休人员',
      bloodType: 'O',
      address: '云南省丽江市古城区香格里大道1217号附1号',
      phone: '13508888144',
      workUnit: '云南省丽江市古城区香格里大道',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"右半结肠及肿瘤"肠管切除标本一段，长11cm，一端切缘周径5cm，另一端切缘周径4cm，距一端切缘7.5cm，另一端切缘3cm处见隆起型肿块，大小3x3x1.5cm。切面灰白，实性，质中。另见阑尾一条，长3cm，直径0.5cm。肠系膜触及淋巴结数枚。另送"小肠切缘"、"结肠切缘"。',
      detailedPathologyDiagnosis:
        '<"右半结肠及肿瘤">腺癌，中分化，癌组织浸润肠壁全层；标本两切缘、环周切缘、"小肠切缘"、"结肠切缘"于镜下未见癌组织；肠系膜淋巴结（0/21）于镜下未见癌转移；阑尾：慢性炎。  Vg：纤维组织阳性  Ag：银纤维阳性',
    },
    {
      reportTime: '2019/4/3 17:33',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('郭伟贤'),
      idCard: desensitizeIdCard('53011119480915081X'),
      hospitalNo: 'ZY030001270459',
      inspectionDate: '20190403',
      patientType: '住院',
      pathologyNo: '2019-03414',
      reportDoctor: '郭姜艳',
      reviewDoctor: '郭姜艳',
      diagnosis: '尿潴留',
      hospitalDiagnosis: '尿潴留',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'Ⅳ',
      clinicalStage: '',
      tStage: '4',
      nStage: '1',
      mStage: '1b',
      occupation: '退(离)休人员',
      bloodType: '未查',
      address: '云南省昆明市盘龙区人民东路昆纺新村33栋1单元5楼20号',
      phone: '-',
      workUnit: '云南省昆明市盘龙区',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"直肠及乙状结肠及肿瘤"肠管切除标本一段，长20cm，一切缘周径9cm，另一切缘周径6cm，距一切缘11cm，另一切缘处见一溃疡隆起型肿块1，肿块大小5.5x5x1cm，切面灰白实性质中，距肿块1（0.3cm）处可见肿块2，肿块2大小2x2x0.8cm，切面灰白实性质中，肠系膜触及淋巴结数枚。',
      detailedPathologyDiagnosis:
        '<"直肠及乙状结肠及肿瘤">腺癌，中分化，癌组织浸润肠壁浅肌层。标本两端切缘于镜下未见癌组织。肠系膜周围淋巴结（0/16）于镜下未见癌转移。  VG:纤维组织阳性。',
    },
    {
      reportTime: '2019/7/26 12:32',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('李芬'),
      idCard: desensitizeIdCard('530103195608200000'),
      hospitalNo: 'ZY020001281768',
      inspectionDate: '20190726',
      patientType: '住院',
      pathologyNo: '2019-08890',
      reportDoctor: '袁婧',
      reviewDoctor: '袁婧',
      diagnosis: '右肺恶性肿瘤',
      hospitalDiagnosis: '右肺恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'Ⅰa',
      clinicalStage: '',
      tStage: '1',
      nStage: '0',
      mStage: '0',
      occupation: '退(离)休人员',
      bloodType: '不详',
      address: '白塔路七彩俊园7幢',
      phone: '13888676201',
      workUnit: '云南省昆明市官渡区银苑小区11幢2单元502号',
      personalHistory:
        '生于原籍，久居白塔路七彩俊园7幢，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有24岁结婚，配偶身体情况：健在，育子1女。',
      menstrualHistory:
        '"初潮14岁，月经  量:中等，颜色:正常	月经情况:52岁绝经,孕2胎产1胎存1胎"',
      fertilityHistory: '月经情况:52岁绝经",孕2胎产1胎存1胎',
      grossAppearance:
        '"右肺上叶结节"肺叶切除标本一叶，大小12x7.5x3cm。于肺门处见支气管残端，长0.5cm。于另一肺表面见两个残腔，较大者2x1x1cm，内见一稍灰白区域，1x0.8cm。小者1x1x0.6cm。另送袋装淋巴结2组。',
      detailedPathologyDiagnosis:
        '<"右肺上叶结节">灰白区域全：见少许浸润性癌，乳头型为主；标本较大残腔壁、较小残腔壁、支气管残端于镜下未见癌组织；"2+4组淋巴结"（0/3）、"11组淋巴结"（0/1）于镜下未见癌转移。  Vg:纤维组织阳性。',
    },
    {
      reportTime: '2019/1/17 11:40',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('范豫琳'),
      idCard: desensitizeIdCard('530103196902260000'),
      hospitalNo: 'ZY020001265048',
      inspectionDate: '20190117',
      patientType: '住院',
      pathologyNo: '2019-00489',
      reportDoctor: '郭姜艳',
      reviewDoctor: '郭姜艳',
      diagnosis: '乙状结肠恶性肿瘤',
      hospitalDiagnosis: '降结肠恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IVA',
      clinicalStage: '',
      tStage: '3',
      nStage: '2b',
      mStage: '1a',
      occupation: '其他',
      bloodType: 'O',
      address: '东郊路141号5幢12楼9号',
      phone: '13888626817',
      workUnit: '不详',
      personalHistory:
        '生于原籍，久居云南省昆明市官渡区东郊路141号5幢12楼9号，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有25岁结婚，配偶身体情况：健在，育1子0女。',
      menstrualHistory: '"初潮14岁，月经  量:，颜色:	月经情况:,孕1胎产1胎存1胎"',
      fertilityHistory: '月经情况:",孕1胎产1胎存1胎',
      grossAppearance:
        '"右肾及右输尿管全长"肾切除标本一个，大小9x5.5x5cm，沿肾门对侧剖开，于肾实质近肾盂处见肿块，肿块大小3.5x3x2.5cm，切面灰白灰红实性质稍软，输尿管长8cm，直径0.5cm，未见明显肿块。',
      detailedPathologyDiagnosis:
        '<"右肾及右输尿管全长">浸润性尿路上皮癌，高级别。标本输尿管断端、血管断端、肾周脂肪组织未见癌组织。  Vg:纤维组织阳性。',
    },
    {
      reportTime: '2019/6/14 10:31',
      inspectionItem: '病理诊断',
      result: '转移性肿瘤',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('郑琴仙'),
      idCard: desensitizeIdCard('532233194809013000'),
      hospitalNo: 'ZY150001277565',
      inspectionDate: '20190614',
      patientType: '住院',
      pathologyNo: '2019-06824',
      reportDoctor: '冉凤明',
      reviewDoctor: '冉凤明',
      diagnosis: '肝部和肝内胆管继发性恶性肿瘤',
      hospitalDiagnosis: '肝部和肝内胆管继发性恶性肿瘤',
      pathologyDiagnosis: '转移性肿瘤',
      tnmStage: 'iv',
      clinicalStage: '',
      tStage: 'X',
      nStage: '0',
      mStage: '1',
      occupation: '工人',
      bloodType: '不详',
      address: '云南省昆明市盘龙区白龙路佳园小区茶苑2栋1单元201号',
      phone: '15758715910',
      workUnit: '-',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"右半结肠及肿瘤"肠管切除标本一段，回肠长5cm，结肠长21cm，回肠切缘周径3cm，结肠切缘周径4cm，距回盲瓣7cm结肠切缘10cm处见一溃疡型肿块，肿块大小4x3x1cm，切面灰白实性质中，于肿块浆膜面见一挂线处，挂线处见一结节，直径约3cm，切面灰白灰黄实性质中，回盲瓣处见阑尾一根，长4cm，直径0.5cm，附网膜组织一堆，总积8x7x6cm，未触及明显结节，肠系膜触及淋巴结数枚，另送"结肠切缘"。',
      detailedPathologyDiagnosis:
        '<"右半结肠及及肿瘤">腺癌，中分化，癌组织浸润肠壁全层达周围脂肪组织；标本回肠切缘、结肠切缘、环周切缘、网膜组织、阑尾及另送"结肠切缘"未见癌组织；系线处结节镜下示癌组织；回肠系膜淋巴结（0/4）、肠系膜动脉根部淋巴结（0/1）未见癌转移；结肠系膜淋巴结（5/13）见癌转移。  Vg：纤维组织阳性。',
    },
    {
      reportTime: '2019/3/19 13:14',
      inspectionItem: '病理诊断',
      result: '移行细胞癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('熊美萍'),
      idCard: desensitizeIdCard('530124194307080000'),
      hospitalNo: 'ZY070001216358',
      inspectionDate: '20190319',
      patientType: '住院',
      pathologyNo: '2019-02649',
      reportDoctor: '郭姜艳',
      reviewDoctor: '郭姜艳',
      diagnosis: '膀胱恶性肿瘤',
      hospitalDiagnosis: '膀胱恶性肿瘤',
      pathologyDiagnosis: '移行细胞癌',
      tnmStage: '-',
      clinicalStage: '',
      tStage: '2a',
      nStage: '0',
      mStage: '0',
      occupation: '农民',
      bloodType: 'A',
      address: '云南省昆明市富民县款庄乡马街村委会大庄村88号',
      phone: '13888905951',
      workUnit: '-',
      personalHistory:
        '生于原籍，久居云南省昆明市富民县款庄乡马街村委会大庄村88号，无疫区、疫情、疫水接触史，否认吸烟史，否认饮酒史',
      maritalHistory: '婚育史： 有18岁结婚，配偶身体情况：健在，育0子5女。',
      menstrualHistory:
        '"初潮13岁，月经  量:中等，颜色:正常	月经情况:已绝经,孕6胎产5胎存5胎"',
      fertilityHistory: '月经情况:已绝经",孕6胎产5胎存5胎',
      grossAppearance:
        '"膀胱肿瘤（主要）"灰白碎组织一堆，总积3x2x1cm，另送"膀胱肿瘤"灰白灰红碎组织一堆，总积2x1x1cm。',
      detailedPathologyDiagnosis:
        '<"膀胱肿瘤(主要)"、"膀胱肿瘤">浸润性癌，待免疫组化协助进一步分型。  Vg：纤维组织阳性  Ag：银纤维阳性',
    },
    {
      reportTime: '2019/7/15 11:51',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('黄庚尧'),
      idCard: desensitizeIdCard('532226195205100000'),
      hospitalNo: 'ZY240001157591',
      inspectionDate: '20190715',
      patientType: '住院',
      pathologyNo: '2019-08240',
      reportDoctor: '张宗梅',
      reviewDoctor: '张宗梅',
      diagnosis: '乙状结肠恶性肿瘤',
      hospitalDiagnosis: '支气管继发恶性肿瘤',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: '4a',
      nStage: '2',
      mStage: '1',
      occupation: '退(离)休人员',
      bloodType: '未查',
      address: '云南省曲靖市罗平县罗雄镇以阁村55号附32号',
      phone: '15887471985',
      workUnit: '云南省曲靖市罗平县罗雄镇以阁村55号附32号',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"左肺下叶"肺叶切除标本一叶，大小13x10x4cm，肺表面见支气管残端，支气管残端旁触及淋巴结数枚，直径0.4-0.6cm，距支气管残端约4cm处见一肿块，肿块大小2x2x1cm，切面灰白实性质中，其余多切面切开未见明显肿块，另送袋装淋巴结四组。',
      detailedPathologyDiagnosis:
        '<"左肺下叶">癌，待免疫组化协助诊断。支气管残端未见癌组织。支气管旁淋巴结（4/8）、"10组L"（3/3）、"11组L"（1/3）见癌转移。"5组L"（0/1）、"9组L"（0/1）未见癌转移。  Vg：纤维组织阳性。',
    },
    {
      reportTime: '2019/9/24 11:04',
      inspectionItem: '病理诊断',
      result: '腺癌，中分化',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('李德惠'),
      idCard: desensitizeIdCard('530128195611020000'),
      hospitalNo: 'ZY160001278969',
      inspectionDate: '20190924',
      patientType: '住院',
      pathologyNo: '2019-12240',
      reportDoctor: '汪钰钦',
      reviewDoctor: '汪钰钦',
      diagnosis: '直肠恶性肿瘤',
      hospitalDiagnosis: '重度营养不良伴消瘦',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IIIB',
      clinicalStage: '',
      tStage: '4',
      nStage: '1',
      mStage: '0',
      occupation: '其他',
      bloodType: '未查',
      address: '云南省昆明市禄劝彝族苗族自治县屏山镇南街村委会南街二村97号',
      phone: '13078707586',
      workUnit: '云南省昆明市禄劝彝族苗族自治县屏山镇南街村委会南街二村97号',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"直肠及肿瘤"肠管切除标本一段，长约23cm，一切缘周径6cm，另一切缘周径7cm，距上切缘6.5cm处囊壁见灰红区域，范围1.5x1cm，距上切缘15.5cm处见肠腔缩窄区，距下切缘1cm处肠腔见广泛灰红区域，范围3x3cm，另见息肉一枚，大小0.5x0.4x0.2cm。肠系膜触及灰黄结节两枚。另送"肠系膜下动脉根部淋巴结"及"上切缘"、"下切缘"。',
      detailedPathologyDiagnosis:
        '<"直肠及肿瘤">腺癌，中分化，癌组织浸润肠壁全层达脂肪组织。息肉：符合管状绒毛状腺瘤，伴腺上皮低级别上皮内瘤变。标本肠管两切缘、环周切缘、"上切缘"、"下切缘"未见癌组织；肠系膜淋巴结（1/13）见癌转移；另见癌结节1枚，"肠系膜动脉根部淋巴结（0/1）未见癌转移。"  Vg：胶原纤维阳性。  Ag：银纤维阳性。',
    },
    {
      reportTime: '2019/10/22 15:12',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('王世铮'),
      idCard: desensitizeIdCard('533421195809132000'),
      hospitalNo: 'ZY190001222672',
      inspectionDate: '20191022',
      patientType: '住院',
      pathologyNo: '2019-13379',
      reportDoctor: '冉凤明',
      reviewDoctor: '冉凤明',
      diagnosis: '结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤中医治疗',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IIa',
      clinicalStage: '',
      tStage: '3',
      nStage: '0',
      mStage: '0',
      occupation: '退(离)休人员',
      bloodType: '未查',
      address: '云南省迪庆藏族自治州香格里拉县虎跳峡镇河西路60号40幢',
      phone: '13988749880',
      workUnit: '不详',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"直肠"固定于泡沫板上息肉一枚，大小1x1x0.8cm，右口测至肛侧每2mm顺序取材。',
      detailedPathologyDiagnosis:
        '<"直肠">绒毛状管状腺瘤，腺上皮呈低级别上皮内瘤变，基底及各切缘均未见肿瘤组织。  Vg：纤维组织阳性。  Vg：银纤维阳性。',
    },
    {
      reportTime: '2019/4/8 11:02',
      inspectionItem: '病理诊断',
      result: '腺癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('王林'),
      idCard: desensitizeIdCard('532201196512283000'),
      hospitalNo: 'ZY090001372776',
      inspectionDate: '20190408',
      patientType: '住院',
      pathologyNo: '2019-03575',
      reportDoctor: '冉凤明',
      reviewDoctor: '冉凤明',
      diagnosis: '升结肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤靶向治疗',
      pathologyDiagnosis: '腺癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: 'x',
      nStage: 'x',
      mStage: '1',
      occupation: '其他',
      bloodType: '未查',
      address: '云南省曲靖市沾益县播乐乡沙石岭村',
      phone: '15812261187',
      workUnit: '云南省曲靖市沾益县播乐乡沙石岭村',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '灰褐组织两块，大者大小2.5x1.5x1.5cm，小者大小1.2x1x1cm，切面均灰黄灰褐实性质中。',
      detailedPathologyDiagnosis:
        '<乙状结肠肿物>管状腺瘤，腺上皮呈高级别上皮内瘤变，含粘膜内腺癌，局部浸润粘膜下层。大、者基底切缘未见癌组织，小者近基底处小于1mm处见少许腺瘤成分。  Vg：胶原纤维阳性。',
    },
    {
      reportTime: '2019/8/9 14:51',
      inspectionItem: '病理诊断',
      result: '转移性癌',
      unit: '',
      referenceValue: '',
      patientName: desensitizeName('王治芳'),
      idCard: desensitizeIdCard('530181195905133000'),
      hospitalNo: 'ZY090001272765',
      inspectionDate: '20190809',
      patientType: '住院',
      pathologyNo: '2019-09764',
      reportDoctor: '张宗梅',
      reviewDoctor: '张宗梅',
      diagnosis: '直肠恶性肿瘤',
      hospitalDiagnosis: '恶性肿瘤终末期靶向治疗',
      pathologyDiagnosis: '转移性癌',
      tnmStage: 'IV',
      clinicalStage: '',
      tStage: '4b',
      nStage: '+',
      mStage: '1',
      occupation: '农民',
      bloodType: 'A',
      address: '云南省安宁市太平镇新邑村119号',
      phone: '-',
      workUnit: '-',
      personalHistory: '',
      maritalHistory: '',
      menstrualHistory: '',
      fertilityHistory: '',
      grossAppearance:
        '"右半结肠及肿瘤"肠管切除标本一段，结肠长11cm，回肠长7cm，结肠切缘周径7cm，回肠切缘周径4cm。距结肠切缘9.5cm处见一肿块，肿块大小2.5x2x1cm。切面灰白，实性，质中。回盲部见阑尾一条，长5cm，直径0.9cm。附网膜组织一堆，总积9x8x2.5cm。于其间未触及明显结节。肠系膜触及淋巴结数枚。',
      detailedPathologyDiagnosis:
        '<"右半结肠及肿瘤">管状腺癌，中分化，癌组织浸润肠壁全层达周围脂肪组织；标本两切缘、网膜组织、阑尾未见癌组织。  Vg：纤维组织阳性。',
    },
  ];

  const startIndex = (page - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const pageData = allData.slice(startIndex, endIndex);

  return {
    data: pageData,
    total: allData.length,
    page,
    pageSize,
  };
}

export default getPathologyData;
